# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/
# ========
name: on_audio_query_web
description: The web implementation of [on_audio_query].
version: 1.6.0
homepage: https://github.com/LucJosin/on_audio_query/tree/main/packages/on_audio_query_web
# pub.dev: https://pub.dev/packages/on_audio_query
# pub.dev (Web): https://pub.dev/packages/on_audio_query_web

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface: ^1.7.0

  # Others
  path: ^1.8.0
  id3: ^1.0.2

  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: OnAudioQueryPlugin
        fileName: on_audio_query_web.dart
