name: on_audio_query
repository: https://github.com/LucJosin/on_audio_query

packages:
  - packages/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  reset:
    run: melos clean && melos bootstrap
    description: Useful to give your workspace a 'fresh start'
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
