name: on_audio_query_web
description: The web implementation of [on_audio_query].
version: 1.4.0
homepage: https://github.com/LucJosin/on_audio_query/tree/master/on_audio_query_web

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface:
    path: ../on_audio_query_platform_interface

  # Others
  path: ^1.8.0
  id3: ^1.0.2
  
  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: OnAudioQueryPlugin
        fileName: on_audio_query_web.dart
