name: on_audio_query_web
description: Web implementation of [on_audio_query].
version: 2.0.0-alpha.0
homepage: https://github.com/LucJosin/on_audio_query/tree/main/on_audio_query_web
# pub.dev: https://pub.dev/packages/on_audio_query
# pub.dev (Web): https://pub.dev/packages/on_audio_query_web
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface:
    path: ../on_audio_query_platform_interface

  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: on_audio_query
    platforms:
      web:
        pluginClass: OnAudioQueryPlugin
        fileName: on_audio_query_web.dart
