# Scripts:
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-tools.sh
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-flutter.sh

name: Dart Analyzer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      melos-version: 3.0.1
    steps:
      # Setup
      - uses: actions/checkout@v2

      # Setup flutter
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
      - run: |
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        shell: bash

      # Install dependencies
      - name: "Install dependencies"
        run: flutter pub get

      # Install tools
      - name: "Install tools"
        run: |
          flutter config --no-analytics
          flutter pub global activate melos ${{env.melos-version}}

      # Melos bootstrap
      - name: "Bootstrap workspace (Melos)"
        run: melos bootstrap

      # Run dart format to ensure formatting is valid
      - name: "Run dart format"
        run: melos exec dart format . --fix

      # Run dart analyzer
      - name: "Run Dart Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./packages
