# Scripts:
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-tools.sh
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-flutter.sh

name: Dart Analyzer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      melos-version: 3.0.1
    steps:
      # Setup
      - uses: actions/checkout@v2

      # Setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install dependencies
      - name: "Install dependencies"
        run: flutter pub get

      # Install tools
      - name: "Install tools"
        run: |
          flutter config --no-analytics
          flutter pub global activate melos ${{env.melos-version}}

      # Melos boostrap
      - name: "Bootstrap workspace (Melos)"
        run: melos bootstrap

      # Run Flutter Format to ensure formatting is valid
      - name: "Run flutter format"
        run: flutter format --set-exit-if-changed .

      # Dart analyzer
      - name: "Run Dart Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./packages

      # Dry run
      - name: "Dry run"
        run: flutter pub publish --dry-run
