# Scripts:
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-tools.sh
#  * fluttercommunity/plus_plugins/.github/workflows/scripts/install-flutter.sh

name: Dart Analyzer
on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.18.0"
      - name: Install dependencies
        run: dart pub get
      - name: "Install flutter"
        run: ./.github/workflows/scripts/install-flutter.sh
      - name: "Install tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap workspace (Melos)"
        run: melos bootstrap
      - name: "Run Dart Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./packages
      - name: "Dry run"
        run: melos publish --dry-run
