name: Dart Analyzer
on:
  push:
    branches:
      - main

jobs:
  plugin-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: dart_analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: on_audio_query/
      - name: Check plugin scores
        env:
          TOTAL: ${{ steps.dart_analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.dart_analysis.outputs.total_max }}
        run: |
          SCORES=$(( $TOTAL / $TOTAL_MAX ))
          if (( $SCORES < 1 ))
          then
            echo Score too low!
            exit 1
          fi
