name: Dart Analyzer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.18.0"
      - name: Install dependencies
        run: dart pub get
      - name: "Bootstrap workspace"
        run: melos bootstrap
      - name: "Run Dart Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./packages
